services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: allotments
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: .
    image: &img allotments
    develop:
      watch:
        - action: sync+restart
          path: ./allotments
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: pyproject.toml
    ports:
      - "8000:8000"
    depends_on:
      - db
  makemigrations:
    image: &img allotments
    command: ["uv", "run", "python", "allotments/manage.py", "makemigrations"]
    profiles:
      - makemigrations
    volumes:
      - .:/app
    depends_on:
      - db
      - web
  migrate:
    image: &img allotments
    command: ["uv", "run", "python", "allotments/manage.py", "migrate"]
    profiles:
      - migrate
    volumes:
      - .:/app
    depends_on:
      - db
      - web
volumes:
  postgres_data: