# Generated by Django 6.1 on 2026-08-27 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allotments', '0001_initial'),
    ]

    operations = [
    ]
