# Generated by Django 6.1 on 2026-08-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotments', '0003_message_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AddField(
            model_name='message',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='anonymous_user',
            field=models.BooleanField(default=False),
        ),
    ]
